name: FridgePal Simple CI/CD

# When should this workflow run?
on:
  push:
    branches: [main, develop] # Run when code is pushed to main or develop
  pull_request:
    branches: [main] # Run when someone creates a PR to main

# Define the jobs (tasks) to run
jobs:
  # Job 1: Check code quality
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest # Use Ubuntu server to run this job

    steps:
      # Step 1: Get the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use Node.js version 18
          cache: 'npm' # Cache npm dependencies for faster builds

      # Step 3: Install all the packages
      - name: Install dependencies
        run: npm install

      # Step 4: Check if code follows style rules
      - name: Run ESLint
        run: npm run lint

  # Job 2: Check TypeScript types
  type-check:
    name: TypeScript Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Check if TypeScript types are correct
      - name: TypeScript check
        run: npx tsc --noEmit

  # Job 3: Check for security vulnerabilities (optional but good practice)
  security-check:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: [code-quality, type-check] # Only run if the above jobs succeed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Check for known security vulnerabilities in dependencies
      - name: Run security audit
        run: npm audit --audit-level moderate
